# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_convert <- function(data, ptype) {
    .Call(`_geom_cpp_convert`, data, ptype)
}

cpp_version_impl <- function() {
    .Call(`_geom_cpp_version_impl`)
}

cpp_test_throw_error <- function() {
    invisible(.Call(`_geom_cpp_test_throw_error`))
}

cpp_intersection <- function(dataLeft, dataRight, ptype) {
    .Call(`_geom_cpp_intersection`, dataLeft, dataRight, ptype)
}

cpp_is_disjoint <- function(dataLeft, dataRight) {
    .Call(`_geom_cpp_is_disjoint`, dataLeft, dataRight)
}

cpp_touches <- function(dataLeft, dataRight) {
    .Call(`_geom_cpp_touches`, dataLeft, dataRight)
}

cpp_intersects <- function(dataLeft, dataRight) {
    .Call(`_geom_cpp_intersects`, dataLeft, dataRight)
}

cpp_crosses <- function(dataLeft, dataRight) {
    .Call(`_geom_cpp_crosses`, dataLeft, dataRight)
}

cpp_is_within <- function(dataLeft, dataRight) {
    .Call(`_geom_cpp_is_within`, dataLeft, dataRight)
}

cpp_contains <- function(dataLeft, dataRight) {
    .Call(`_geom_cpp_contains`, dataLeft, dataRight)
}

cpp_overlaps <- function(dataLeft, dataRight) {
    .Call(`_geom_cpp_overlaps`, dataLeft, dataRight)
}

cpp_equals <- function(dataLeft, dataRight) {
    .Call(`_geom_cpp_equals`, dataLeft, dataRight)
}

cpp_covers <- function(dataLeft, dataRight) {
    .Call(`_geom_cpp_covers`, dataLeft, dataRight)
}

cpp_is_covered_by <- function(dataLeft, dataRight) {
    .Call(`_geom_cpp_is_covered_by`, dataLeft, dataRight)
}

cpp_offset_curve <- function(x, width, quadSegs, endCapStyle, joinStyle, mitreLimit, to) {
    .Call(`_geom_cpp_offset_curve`, x, width, quadSegs, endCapStyle, joinStyle, mitreLimit, to)
}

cpp_buffer <- function(x, width, quadSegs, endCapStyle, joinStyle, mitreLimit, singleSided, to) {
    .Call(`_geom_cpp_buffer`, x, width, quadSegs, endCapStyle, joinStyle, mitreLimit, singleSided, to)
}

cpp_project <- function(dataLeft, dataRight) {
    .Call(`_geom_cpp_project`, dataLeft, dataRight)
}

cpp_project_normalized <- function(dataLeft, dataRight) {
    .Call(`_geom_cpp_project_normalized`, dataLeft, dataRight)
}

cpp_interpolate <- function(data, ptype, distance) {
    .Call(`_geom_cpp_interpolate`, data, ptype, distance)
}

cpp_interpolate_normalized <- function(data, ptype, distance) {
    .Call(`_geom_cpp_interpolate_normalized`, data, ptype, distance)
}

cpp_area <- function(x) {
    .Call(`_geom_cpp_area`, x)
}

cpp_length <- function(x) {
    .Call(`_geom_cpp_length`, x)
}

cpp_distance <- function(x, y) {
    .Call(`_geom_cpp_distance`, x, y)
}

cpp_is_empty <- function(data) {
    .Call(`_geom_cpp_is_empty`, data)
}

cpp_is_simple <- function(data) {
    .Call(`_geom_cpp_is_simple`, data)
}

cpp_has_z <- function(data) {
    .Call(`_geom_cpp_has_z`, data)
}

cpp_is_closed <- function(data) {
    .Call(`_geom_cpp_is_closed`, data)
}

cpp_validate_provider <- function(data) {
    .Call(`_geom_cpp_validate_provider`, data)
}

