# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

geomcpp_version_impl <- function() {
    .Call(`_geom_geomcpp_version_impl`)
}

geomcpp_test_throw_error <- function() {
    invisible(.Call(`_geom_geomcpp_test_throw_error`))
}

geomcpp_intersection <- function(dataLeft, dataRight, ptype) {
    .Call(`_geom_geomcpp_intersection`, dataLeft, dataRight, ptype)
}

geomcpp_binary_predicate <- function(dataLeft, dataRight, predicate) {
    .Call(`_geom_geomcpp_binary_predicate`, dataLeft, dataRight, predicate)
}

geomcpp_buffer <- function(data, ptype, width, quadSegs, endCapStyle, joinStyle, mitreLimit, singleSided) {
    .Call(`_geom_geomcpp_buffer`, data, ptype, width, quadSegs, endCapStyle, joinStyle, mitreLimit, singleSided)
}

geomcpp_convert <- function(data, ptype) {
    .Call(`_geom_geomcpp_convert`, data, ptype)
}

geomcpp_is_empty <- function(data) {
    .Call(`_geom_geomcpp_is_empty`, data)
}

geomcpp_validate_provider <- function(data) {
    .Call(`_geom_geomcpp_validate_provider`, data)
}

