# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

geos_test_roundtrip_wkt <- function(wkt) {
    .Call(`_geom_geos_test_roundtrip_wkt`, wkt)
}

geos_version_impl <- function() {
    .Call(`_geom_geos_version_impl`)
}

